# Site settings
title: Blog
description: Pip's personal blog.
url: "https://pipwitheridge.github.io"   
baseurl: "/blog"                        
# Build settings
markdown: kramdown
permalink: /:title/